module.exports = {
  projects: [
    '<rootDir>/apps/black-dashboard',
    '<rootDir>/libs/configuration',
    '<rootDir>/libs/rule-engine',
    '<rootDir>/libs/logging',
    '<rootDir>/libs/error-handling',
    '<rootDir>/libs/actions',
    '<rootDir>/libs/common',
    '<rootDir>/libs/http-service',
    '<rootDir>/libs/foundation',
    '<rootDir>/libs/validation',
    '<rootDir>/libs/notifications',
    '<rootDir>/libs/version-check',
    '<rootDir>/libs/analytics',
    '<rootDir>/libs/accounts/accounts-ui',
    '<rootDir>/libs/accounts/types',
    '<rootDir>/libs/accounts/accounts-service',
    '<rootDir>/apps/accounts-api',
    '<rootDir>/libs/types',
    '<rootDir>/apps/admin',
    '<rootDir>/libs/api/accounts-bl',
  ],
};
